name: DockerDemo

on:
  push:
    branches:
      - master


jobs:
  DockerDemo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0'

      - name: Set up Docker
        uses: docker/setup-docker@v2  

      - name: Run Bash 
        run: 
          ./DockerDemo.bash
        
