name: DockerDemo

on:
  push:
    branches:
      - master


jobs:
  DockerDemo:
    runs-on: ubuntu-latest

 #   container:
 #     image: openjdk:8-jdk

  
    steps:
      - name: Checkout code
        uses: actions/Checkout@master

      # Step 1: 配置Java 8环境
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
    
      
#      - name: Install Docker
#        run: |
#          curl -fsSL https://get.docker.com -o get-docker.sh
#          sh get-docker.sh
      
      # Step 2: 配置Docker环境
      - name: Set up Docker
        uses: docker/build-push-action@v2

          
 #     - name: Start Docker
  #      run: |
#          service docker start

      - name: Run Bash 
        run: 
          ./DockerDemo.bash
        
