name: DockerDemo

on:
  push:
    branches:
      - master


jobs:
  DockerDemo:
    runs-on: ubuntu-latest

    container:
      image: openjdk:8-jdk
    
    steps:
      - name: Checkout code
        uses: actions/Checkout@master

      # Step 1: 配置Docker环境
      - name: Install Docker
        run: |
          apt-get update
          apt-get -y install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt-get update
          apt-get -y install docker-ce

      - name: Run Bash 
        run: 
          ./DockerDemo.bash
        
